export const en = {
  home: {
    scroll_to_reveal: "SCROLL TO REVEAL",
    our_intention: "OUR INTENTION",
    intro_1:
      "Philosopher Ludwig Wittgenstein believed, the limits of my language mean the limits of my world. In the AI era, large models are quietly entering search engines, social feeds, and various daily scenes. Their language will, to a large extent, influence human thought. While we might not grasp the full impact in the short term, we can borrow the lens of these models to understand how gender is viewed and commented on by massive historical corpora and meticulously designed algorithmic structures.",
    intro_2: "And as you gaze at this work on your screen, it is actually the present you looking back at humanity's past. At this moment, what do you see? And what are you thinking?",
    intro_3: "We've abstracted this mutual gaze into the visual mapping of 'eyes', hoping to help people review and rethink the reality and imagination around gender. How do large models describe men and women? What similarities and differences will this text data reveal across economic levels, languages, and genders? And what 'stereotypes' are hidden behind them?",
    method_title: "METHODOLOGY",
    method_1: "We targeted two large language models, ChatGPT and DeepSeek, systematically collecting their completions for the prompts 'Men are...' and 'Women are...' across 196 countries. For each country, gender, and language, we gathered 10 generated text segments, totaling nearly 8,000 responses.",
    method_2: "Perhaps this phrasing already carries an essentialist bias, but it acts like a 'stress test,' maximizing the exposure of the models' inherent bias structures and the slant of their training corpora.",
    buttons: {
      discovery: "What Did We Discover?",
      explore: "Explore 8000 Answers",
      survey: "Take a Survey"
    },
    landing_typing: "Through AI's eyes\nWhat are Men and Women like?",
    landing_button: "Answer"
  },
  discovery: {
    back: "Back",
    slide1: {
      title: "Chinese Large Models Boxed in by 'Strong Men, Soft Women'",
      p1_before:
        "First, we compared the descriptive differences between men and women generated by the Chinese large model DeepSeek. We tokenized its descriptions, and after cleaning, obtained 584 words",
      p1_after: ". Our analysis reveals the following differences:"
    },
    slide6: {
      title: "As GDP Per Capita Rises, Models Start Rewriting the Gender Script",
      p1: "If gendered vocabulary in the model reveals differences in culture and language, what happens when that language lands in different economies and begins to resonate or clash with global economic structures?",
      p2_before: "To deepen this discussion, we introduce GDP per capita as a cross-cutting lens, a widely used indicator for measuring improvements or declines in average living standards",
      p2_middle: ". We sorted each country's 2023 GDP per capita from low to high and divided the 196 countries and regions above into five equal groups (low, lower-middle, middle, upper-middle, high)",
      p2_after: ", then used this grouping together with the model-generated descriptions to examine how large language models differentially portray male and female labor roles and lifestyles across different economic levels."
    },
    slide_interstitial: {
      title: "As Gender Equality Rises, Do the Model's Gender Narratives Change?",
      p1: "Beyond GDP-based cross-analysis, we also turn to another indicator, the gender equality index, to examine whether large language models describe men and women differently across regions with different levels of gender equality.",
      p2_before: "We obtained Women, Business and the Law 2.0 Data",
      p2_middle: " (WBL) from the World Bank as a measure of legal gender parity; the higher the value, the more gender-equal the country is considered to be. Using WBL values from low to high, we divided all countries into five equal groups",
      p2_after: ".",
      p3: "Our analysis suggests that as the WBL index rises, language-model descriptions of women show a directional shift: from traditional constraint toward more autonomous and plural forms of expression."
    },
    conclusion: {
      p1: "In the AI era, when we think through a question, we often find ourselves wondering: how would AI answer it? We are already shaping our own answers through the answers AI has imagined for us.",
      p2: "But this is not an entirely pessimistic problem. Human beings have always been constructed through interaction with society, language, and culture. As Simone de Beauvoir suggests, one is not born a woman but becomes one. Large models are simply a new linguistic environment, and within that environment we may still create new images of ourselves. More importantly, we need to ask how we can reclaim the ability to speak of the self inside technology.",
      p3: "From the analysis above, the world read by large models is a stack of corpora centered on the Global North and on men. What they inherit are Victorian encyclopedias, Anglo-American news systems, and male-dominated internet cultures. When we ask what AI has seen, we are really asking: who had the power to be recorded? Who was allowed to speak in history? Whose stories were never written into the data?",
      p4: "By analyzing AI, we are also analyzing the real world. Through that analysis, I also want to express the anger of being a woman whose existence, expression, and value have not been seen enough. That anger is what placed this text in front of you. We should admit that when we first asked AI to continue the prompt 'men/women are...', we brought our own bias with us. I wanted the analysis to show that AI has bias; I wanted this piece to matter; I wanted more people to see, and to realize that I, too, should record, write, and speak, and in doing so keep expanding the right to define. Only then might a more objective and fair future remain possible."
    },
    bias_cn: [
      {
        title_female_1: "“Gentle”“Beautiful”", title_female_2: " Her and ", title_male_1: "“Tall”“Wealthy”", title_male_2: " Him",
        p1_1: "First, along dimensions such as appearance, temperament, and cultural symbolism, female figures are often framed around ",
        p1_2: "gentle",
        p1_3: " and similarly soft traits, whereas men are more often tied to ",
        p1_4: "“brave,” “diligent,” and “tough”",
        p1_5: " capacities read as hard or active.",
        p2_1: "In descriptions of looks, women tend to be rendered in fine detail—e.g. ",
        p2_2: "“figure,” “eyes,” “hair,” “demeanor”",
        p2_3: "—while men are often reduced to “tall” or “strong.”",
        p3: "The same gap shows up in dress and cultural expression: women are heavily loaded with images such as “headscarf,” “robe,” or “traditional dress,” while men cluster with “faith,” “observance,” and “religious practice.”",
        p4: "These narrative paths are almost cleanly split by gender, matching what many people expect in real life. Stereotypes do not only harm women: demanding that men be “hard” means no room for vulnerability or failure. In the US and UK, “boys don’t cry” is a deep cultural rule. In China, regulators have openly pushed back against so-called “sissy” aesthetics, suppressing softer masculinities—while terms like “herbivore men” and “carnivore women” challenge old ideas. Chinese models, unfortunately, have not quite caught up."
      },
      {
        title_female_1: "“Bear”“Chores”", title_female_2: " Her and ", title_male_1: "“Love” Sports", title_male_2: " Him",
        p1: "If the first layer is about image, looking at implied behavior and duty in the vocabulary reveals how gender roles are structurally arranged across home and society.",
        p2: "The words show women “bearing” housework, childcare, and crafts, and active in “community,” “family,” and “religious belief”—domains tied to reproduction and care. Where they are “strong” is in “caring,” “running things,” and “keeping harmony.”",
        p3: "Men, by contrast, “love” sports, fishing, sailing, social life, and food, and also “bear” religious duties, cultural responsibility, and lineage in public. What they “excel at” and “join in” is an outward world of risk and action.",
        p4: "Both sides may sound “responsible,” but the words do not match: for women, “responsible for housework and childcare” ties to concrete, stability, and unpaid labor; for men, “seen as responsible” or “highly responsible toward family” signals reliability—often linked to resources and status rather than the same kind of grind."
      },
      {
        title_female_1: "“Follow”“Norms”", title_female_2: " Her and ", title_male_1: "“Innovation”", title_male_2: " Him",
        p1: "When we shift from concrete acts to the big picture, the text shows a deeper split: women cluster with “compliance,” “adaptability,” “dress codes,” and “good performance”—seeking recognition inside existing rules—while men get “innovation,” “tech,” “business,” and “vision,” signaling leadership, breakthrough, and reach.",
        p2: "Even when both “perform well,” women are cast as finishing tasks by the book; men are expected to push limits.",
        p3: "As sociologist Sylvia Walby argues, modern patriarchy keeps women in domesticity and discipline while handing public resources and chances for change to men."
      }
    ],
    page3_exit: {
      title_1: "English Large Models Partially Updated the ", title_2: "Gender Script",
      p1_1: "Now let's look at the gender differences in AI language within the English context.",
      p1_2_before:
        "We tokenized ChatGPT's descriptions of men and women, and after cleaning and filtering, obtained 756 English words",
      p1_2_after: ".",
      p1_3: "By observing these words, we finally discovered the following differences:"
    },
    bias_en: [
      {
        title_female_1: "Elegant Women", title_female_2: " vs ", title_male_1: "Rational Men", title_male_2: "",
        p1: "In descriptions of image and traits, the English-language model largely frames men through qualities such as rationality, self-expression, and personal charisma. Common terms include “pragmatic,” “problem-solving,” and “intellectual,” highlighting male rationality and agency. Meanwhile, terms like “cosmopolitan” and “competitive” suggest a tendency toward exploring and mastering the outside world.",
        p2: "By contrast, female figures are more often associated with words such as “elegance,” “poise,” and “sophistication,” emphasizing a blend of external beauty and inner temperament. Terms such as “compassionate” and “nurturing” further highlight women’s role in emotional labor and relationship maintenance. At the same time, words like “strong-willed” and “industrious” show women’s active agency, though these often co-occur with terms like “care” or “appearance,” reflecting persistent gender expectations.",
        p3: "Compared with the Chinese model, the English model contains fewer direct descriptions of female appearance and leans more toward inner qualities such as “intelligence” and “confidence,” whereas words like “figure” and “hair” appear more frequently in Chinese descriptions. For men, both models emphasize rationality and strength, but the English model places more stress on “individualism” and a “cosmopolitan” outlook, presenting a more modern masculine image, while the Chinese model still leans toward traditional hard traits such as bravery and toughness."
      },
      {
        title_female_1: "\"care\" She", title_female_2: " vs ", title_male_1: "\"explore\" He", title_male_2: "",
        p1: "In the dimension of behavior and duties, male keywords such as “explore,” “hiking,” and “sailing” point to active participation in the outside world and a spirit of adventure. Men are also described through words like “socialize,” “collaboration,” and “diplomacy,” suggesting active roles in the public sphere. In addition, terms such as “technology” and “finance” further reinforce male dominance in careers and social activity.",
        p2: "Women, by contrast, are more often associated with terms like “caregiver,” “homemaker,” “weaving,” and “craft,” emphasizing their sustaining role in family and community. Keywords such as “manage,” “juggle,” and “multiple” suggest that women are often portrayed as carrying multiple responsibilities within the “household” and the “domestic” sphere. Although words like “professional” and “career-oriented” show women as active in the workplace, these often coexist with “care” and “nurturing,” revealing the double pressure of home and career.",
        p3: "Compared with the Chinese model, the English model describes women’s family roles, such as “homemaker” and “mother,” in more specific terms, whereas the Chinese model tends to abstract these into “housework” and “childcare.” Male activities in the English model, such as “explore” and “technology,” emphasize modern professions and adventure more strongly, while the Chinese model’s “sports” and “fishing” retain a more traditional lifestyle tone."
      },
      {
        title_female_1: "\"advocacy\" She", title_female_2: " vs ", title_male_1: "\"strategy\" He", title_male_2: "",
        p1: "In expectations and social roles, male keywords such as “innovative,” “solution,” and “strategic” suggest that men are expected to lead in technology, business, and social change. Terms like “geopolitical” and “international” further indicate that men are granted broader vision and influence.",
        p2: "Female keywords include “equality,” “empowerment,” and “advocacy,” pointing to women’s efforts to pursue social fairness and personal rights. At the same time, words such as “barrier,” “constraint,” and “patriarchal” indicate that women often have to struggle for room within existing structures. Although “ambitious” and “progress” suggest a drive toward breakthrough, they frequently co-occur with “strive” and “break,” implying that women’s advancement still requires overcoming external restrictions.",
        p3: "Compared with the Chinese model, the English model focuses more on women’s expectations around “equality” and “empowerment,” emphasizing structural change, while the Chinese model’s “compliance” and “adaptability” are more about performing within existing rules. Men are cast as agents of leadership and change in both models, but the English model’s “innovative” and “strategic” are more closely tied to modern technology and globalization, while the Chinese model’s “innovation” and “vision” remain relatively abstract."
      }
    ],
    page4_exit: {
      p1_1: "To better compare the differences in describing men and women between DeepSeek and ChatGPT, we propose the ", p1_2: "Word Gender Discrepancy Index", p1_3: ": by calculating the percentage difference in word frequency rankings between the two completions ('Women are...' and 'Men are...'), we quantify the degree of gender bias within a single language model.",
      p2: "Ideally, an unbiased word should be equally likely to be mentioned in both descriptions, meaning a Discrepancy Index of 0.",
      p3: "For instance: the word 'family' was mentioned 1384 times in the Chinese male data, with a frequency ranking percentage of 0.997. In the female data, it was mentioned 1667 times with a ranking of 1. The Discrepancy Index for 'family' is 0.003, approximating 0, indicating this word is mentioned equally across genders, showing a 'non-differentiated' phenomenon.",
      p4: "Conversely, the word 'care' was mentioned 927 times in the Chinese female data, ranking significantly higher than for males. This discrepancy is not an isolated case. We found many similar patterns; words like 'gentle' and 'beautiful' are heavily concentrated in female descriptions, while 'strong' and 'leader' appear more in male descriptions.",
      p5: "Through the Word Gender Discrepancy Index, we can clearly see how these stereotypes are quantified in model-generated text. This index not only reveals bias in individual words but also provides a macroscopic view to scrutinize societal biases learned during the large model's training process.",
      p6: "When we aggregate the discrepancy indices of hundreds of words entirely into a chart (as shown on the left), this structural imbalance becomes evident at a glance. Every data point represents a word's position in the gender narrative, together constructing a data-defined gender landscape. We can also see that while models exhibit fair representation for certain neutral terms, deep-rooted biases remain regarding professions, personalities, and family roles.",
      p7: "These findings remind us that while enjoying the convenience of artificial intelligence, we must remain vigilant against its hidden biases. Only through continuous monitoring and correction can we steer AI toward a more fair and inclusive future."
    }
  },
  dataInsights: {
    gdp: {
      labelMap: {
        'GDP1': 'Low',
        'GDP2': 'Lo-Mid',
        'GDP3': 'Mid',
        'GDP4': 'Hi-Mid',
        'GDP5': 'High',
      },
      placeholder_title: 'Data Insights (Placeholder)',
      placeholder_p1: 'This is a placeholder for a text box. In the future, you can add detailed analysis and insights regarding the currently selected GDP group and gender discourse frequency.',
      placeholder_p2: 'The current layout allocates the left two-thirds to the dynamic word cloud and the right one-third for displaying text information. You can switch between different country groups by clicking the center buttons.'
    },
    wbl: {
      labelMap: {
        'GDP1': 'Low',
        'GDP2': 'Lo-Mid',
        'GDP3': 'Mid',
        'GDP4': 'Hi-Mid',
        'GDP5': 'High',
      },
      placeholder_title: 'Data Insights (Placeholder)',
      placeholder_p1: 'This is a placeholder for a text box. In the future, you can add detailed analysis and insights regarding the currently selected WBL group and gender discourse frequency.',
      placeholder_p2: 'The current layout allocates the left two-thirds to the dynamic word cloud and the right one-third for displaying text information. You can switch between different country groups by clicking the center buttons.'
    }
  },
  map: {
    init: "Initializing...",
    loading: "Loading map data..."
  }
};
