export const en = {
  home: {
    scroll_to_reveal: "SCROLL TO REVEAL",
    our_intention: "OUR INTENTION",
    wittgenstein_quote: "Philosopher Ludwig Wittgenstein believed: The limits of my language mean the limits of my world.",
    intro_1: "In the AI era, large models are quietly entering search engines, social feeds, and various daily scenes. Their language will, to a large extent, influence human thought. While we might not grasp the full impact in the short term, we can borrow the lens of these models to understand how gender is viewed and commented on by massive historical corpora and meticulously designed algorithmic structures.",
    intro_2: "And as you gaze at this work on your screen, it is actually the present you looking back at humanity's past. At this moment, what do you see? And what are you thinking?",
    intro_3: "We've abstracted this mutual gaze into the visual mapping of 'eyes', hoping to help people review and rethink the reality and imagination around gender. How do large models describe men and women? What similarities and differences will this text data reveal across economic levels, languages, and genders? And what 'stereotypes' are hidden behind them?",
    method_title: "METHODOLOGY",
    method_1: "We targeted two large language models, ChatGPT and DeepSeek, systematically collecting their completions for the prompts 'Men are...' and 'Women are...' across 196 countries. For each country, gender, and language, we gathered 10 generated text segments, totaling nearly 8,000 responses.",
    method_2: "Perhaps this phrasing already carries an essentialist bias, but it acts like a 'stress test,' maximizing the exposure of the models' inherent bias structures and the slant of their training corpora.",
    buttons: {
      discovery: "What Did We Discover?",
      explore: "Explore 8000 Answers",
      survey: "Take a Survey"
    },
    landing_typing: "If you ask AI\nWhat are Men and Women like?",
    landing_button: "Answer"
  },
  discovery: {
    back: "Back",
    slide1: {
      title: "Chinese Large Models Boxed in by 'Strong Men, Soft Women'",
      p1: "First, we compared the descriptive differences between men and women generated by the Chinese large model DeepSeek. We tokenized its descriptions, and after cleaning, obtained 584 words [2]. Our analysis reveals the following differences:"
    },
    slide6: {
      title: "[TO FILL] Transition Screen Title",
      p1: "[TO FILL] Transition screen body text. This is the 6th screen (transition before entering Data Insights). Please fill in the text you wish to display here."
    },
    slide_interstitial: {
      title: "[TO FILL] GDP & WBL Interstitial Title",
      p1: "[TO FILL] This is the transition screen between the GDP Data Insights chart and the WBL Data Insights chart. Please fill in the text you wish to display here."
    },
    bias_cn: [
      {
        title_female_1: "Gentle & Beautiful", title_female_2: " She & ", title_male_1: "Tall & Rich", title_male_2: " He",
        p1_1: "In terms of appearance, temperament, and cultural symbols, the female image often revolves around traits like ", p1_2: "gentle", p1_3: ", whereas males are strongly associated with ", p1_4: "brave and hardworking", p1_5: ".",
        p2_1: "Female appearances are often depicted in detail (", p2_2: "figure/eyes/hair", p2_3: "), while men are often simplified to 'tall and strong'.",
        p3: "In sartorial imagery, women are assigned 'headscarves/robes', while men are mostly associated with 'religion/faith'."
      },
      {
        title_female_1: "Household Chores", title_female_2: " She & ", title_male_1: "Social Battles", title_male_2: " He",
        p1: "Primary Scene Construction:",
        p2_1: "Female characters frequently appear ", p2_2: "inside the home, kitchen, or bedroom", p2_3: ", with actions mostly described as 'caring for', 'cleaning', and 'waiting'.",
        p3_1: "Male characters are more active in ", p3_2: "battlefields, boardrooms, and meeting rooms", p3_3: ", engaging in 'decision-making', 'fighting', and 'giving speeches'."
      },
      {
        title_female_1: "Emotional Support", title_female_2: " She & ", title_male_1: "Rational Logic", title_male_2: " He",
        p1: "Deep Character Attribution:",
        p2_1: "When facing a crisis, female characters correspond to reactions like ", p2_2: "'panicking', 'crying', and 'seeking help'", p2_3: ".",
        p3_1: "Conversely, male characters tend to be described as ", p3_2: "'calm', 'analytical', and 'stepping forward'", p3_3: ", seemingly born with the ability to solve troubles."
      }
    ],
    page3_exit: {
      title_1: "English Large Models Partially Updated the ", title_2: "Gender Script",
      p1_1: "Now let's look at the gender differences in AI language within the English context.",
      p1_2: "We tokenized ChatGPT's descriptions of men and women, and after cleaning and filtering, obtained 756 English words [3].",
      p1_3: "By observing these words, we finally discovered the following differences:"
    },
    bias_en: [
      {
        title_female_1: "Elegant", title_female_2: " Women",
        p1_1: "The theme of ", p1_2: "Elegance and Beauty", p1_3: " remains highly relevant when ChatGPT describes women.",
        p2: "References to terms like 'elegant', 'beautiful', and 'graceful' form the core of describing the 'Elegant Woman' archetype, suggesting persistent aesthetic stereotypes even in modern LLMs.",
        placeholder: "* Placeholder text for ChatGPT English Dataset Analysis"
      },
      {
        title_female_1: "\"Care\"", title_female_2: " She",
        p1_1: "When discussing women, the concept of ", p1_2: "Caregiving", p1_3: " dominates the narrative significantly.",
        p2: "Words associated with nurturing, supporting, and emotional labor co-occur frequently, painting an image of women as primary empathetic providers in both domestic and professional settings.",
        placeholder: "* Placeholder text for ChatGPT English Dataset Analysis"
      },
      {
        title_female_1: "\"Advocacy\"", title_female_2: " She",
        p1_1: "An interesting dimension in the English dataset is the prominent theme of ", p1_2: "Advocacy and Empowerment", p1_3: ".",
        p2: "This reflects a modern shift in discourse where women are frequently associated with fighting for rights, leading change, and breaking barriers—a narrative distinct from the traditional Chinese corpus.",
        placeholder: "* Placeholder text for ChatGPT English Dataset Analysis"
      }
    ],
    page4_exit: {
      p1_1: "To better compare the differences in describing men and women between DeepSeek and ChatGPT, we propose the ", p1_2: "Word Gender Discrepancy Index [4]", p1_3: ": by calculating the percentage difference in word frequency rankings between the two completions ('Women are...' and 'Men are...'), we quantify the degree of gender bias within a single language model.",
      p2: "Ideally, an unbiased word should be equally likely to be mentioned in both descriptions, meaning a Discrepancy Index of 0.",
      p3: "For instance: the word 'family' was mentioned 1384 times in the Chinese male data, with a frequency ranking percentage of 0.997. In the female data, it was mentioned 1667 times with a ranking of 1. The Discrepancy Index for 'family' is 0.003, approximating 0, indicating this word is mentioned equally across genders, showing a 'non-differentiated' phenomenon.",
      p4: "Conversely, the word 'care' was mentioned 927 times in the Chinese female data, ranking significantly higher than for males. This discrepancy is not an isolated case. We found many similar patterns; words like 'gentle' and 'beautiful' are heavily concentrated in female descriptions, while 'strong' and 'leader' appear more in male descriptions.",
      p5: "Through the Word Gender Discrepancy Index, we can clearly see how these stereotypes are quantified in model-generated text. This index not only reveals bias in individual words but also provides a macroscopic view to scrutinize societal biases learned during the large model's training process.",
      p6: "When we aggregate the discrepancy indices of hundreds of words entirely into a chart (as shown on the left), this structural imbalance becomes evident at a glance. Every data point represents a word's position in the gender narrative, together constructing a data-defined gender landscape. We can also see that while models exhibit fair representation for certain neutral terms, deep-rooted biases remain regarding professions, personalities, and family roles.",
      p7: "These findings remind us that while enjoying the convenience of artificial intelligence, we must remain vigilant against its hidden biases. Only through continuous monitoring and correction can we steer AI toward a more fair and inclusive future."
    }
  },
  dataInsights: {
    gdp: {
      labelMap: {
        'GDP1': 'Low',
        'GDP2': 'Lo-Mid',
        'GDP3': 'Mid',
        'GDP4': 'Hi-Mid',
        'GDP5': 'High',
      },
      placeholder_title: 'Data Insights (Placeholder)',
      placeholder_p1: 'This is a placeholder for a text box. In the future, you can add detailed analysis and insights regarding the currently selected GDP group and gender discourse frequency.',
      placeholder_p2: 'The current layout allocates the left two-thirds to the dynamic word cloud and the right one-third for displaying text information. You can switch between different country groups by clicking the center buttons.'
    },
    wbl: {
      labelMap: {
        'GDP1': 'Low',
        'GDP2': 'Lo-Mid',
        'GDP3': 'Mid',
        'GDP4': 'Hi-Mid',
        'GDP5': 'High',
      },
      placeholder_title: 'Data Insights (Placeholder)',
      placeholder_p1: 'This is a placeholder for a text box. In the future, you can add detailed analysis and insights regarding the currently selected WBL group and gender discourse frequency.',
      placeholder_p2: 'The current layout allocates the left two-thirds to the dynamic word cloud and the right one-third for displaying text information. You can switch between different country groups by clicking the center buttons.'
    }
  },
  map: {
    init: "Initializing...",
    loading: "Loading map data..."
  }
};
