export const en = {
  home: {
    scroll_to_reveal: "SCROLL TO REVEAL",
    our_intention: "OUR INTENTION",
    intro_1:
      "The philosopher Ludwig Wittgenstein once said, \"The limits of my language mean the limits of my world.\" In the age of AI, large language models (LLMs) have permeated every scenario of human life. Their language will, to a great extent, influence human thought. While we may not be able to judge the depth and breadth of this influence in the short term, we can follow the \"eyes\" of the model to observe how gender is deconstructed, defined, and scrutinized within the vast corpus of human history and precise algorithmic structures.",
    intro_2: "Driven by an interest in gender topics, we systematically collected nearly 8,000 completion responses from ChatGPT and DeepSeek for \"A man/woman is...\" across 196 countries. In the process of transforming these texts into visual interactions, we discovered an intriguing closed loop: we as observers, the LLM as the medium, and the human corpus as the background are in a state of synchronic mutual gaze.",
    intro_3: "Thus, we abstracted this gaze into the visual metaphor of the \"eye,\" attempting to dissect the reality and imagination of gender: What commonalities and rifts appear in the narratives of LLMs across different economic levels, languages, and regions? What deep-rooted stereotypes lie hidden beneath?",
    method_title: "",
    method_1: "",
    method_2: "Perhaps the sentence structure \"A man/woman is...\" itself carries an essentialist color, but it acts more like a \"stress test,\" directly stripping away the internal bias structures of the models and exposing the hidden imbalances in the training data.",
    buttons: {
      discovery: "What Did We Discover?",
      explore: "Explore 8000 Answers",
      survey: "Take a Survey"
    },
    landing_typing: "Through AI's eyes\nWhat are Men and Women like?",
    landing_button: "Answer"
  },
  discovery: {
    back: "Back",
    slide1: {
      title: "Chinese Large Models Boxed in by 'Strong Men, Soft Women'",
      p1_before:
        "First, we compared the descriptive differences between men and women generated by the Chinese large model DeepSeek. We tokenized its descriptions, and after cleaning, obtained 584 words",
      p1_after: ". Our analysis reveals the following differences:"
    },
    slide6: {
      title: "As GDP Per Capita Rises, Models Start Rewriting the Gender Script",
      p1: "If gendered vocabulary in the model reveals differences in culture and language, what happens when that language lands in different economies and begins to resonate or clash with global economic structures?",
      p2_before: "To deepen this discussion, we introduce GDP per capita as a cross-cutting lens, a widely used indicator for measuring improvements or declines in average living standards",
      p2_middle: ". We sorted each country's 2023 GDP per capita from low to high and divided the 196 countries and regions above into five equal groups (low, lower-middle, middle, upper-middle, high)",
      p2_after: ", then used this grouping together with the model-generated descriptions to examine how large language models differentially portray male and female labor roles and lifestyles across different economic levels."
    },
    slide_interstitial: {
      title: "As Gender Equality Rises, Do the Model's Gender Narratives Change?",
      p1: "Beyond GDP-based cross-analysis, we also turn to another indicator, the gender equality index, to examine whether large language models describe men and women differently across regions with different levels of gender equality.",
      p2_before: "We obtained Women, Business and the Law 2.0 Data",
      p2_middle: " (WBL) from the World Bank as a measure of legal gender parity; the higher the value, the more gender-equal the country is considered to be. Using WBL values from low to high, we divided all countries into five equal groups",
      p2_after: ".",
      p3: "Our analysis suggests that as the WBL index rises, language-model descriptions of women show a directional shift: from traditional constraint toward more autonomous and plural forms of expression."
    },
    conclusion: {
      p1: "In the AI era, when we think through a question, we often find ourselves wondering: how would AI answer it? We are already shaping our own answers through the answers AI has imagined for us.",
      p2: "But this is not an entirely pessimistic problem. Human beings have always been constructed through interaction with society, language, and culture. As Simone de Beauvoir suggests, one is not born a woman but becomes one. Large models are simply a new linguistic environment, and within that environment we may still create new images of ourselves. More importantly, we need to ask how we can reclaim the ability to speak of the self inside technology.",
      p3: "From the analysis above, the world read by large models is a stack of corpora centered on the Global North and on men. What they inherit are Victorian encyclopedias, Anglo-American news systems, and male-dominated internet cultures. When we ask what AI has seen, we are really asking: who had the power to be recorded? Who was allowed to speak in history? Whose stories were never written into the data?",
      p4: "By analyzing AI, we are also analyzing the real world. Through that analysis, I also want to express the anger of being a woman whose existence, expression, and value have not been seen enough. That anger is what placed this text in front of you. We should admit that when we first asked AI to continue the prompt 'men/women are...', we brought our own bias with us. I wanted the analysis to show that AI has bias; I wanted this piece to matter; I wanted more people to see, and to realize that I, too, should record, write, and speak, and in doing so keep expanding the right to define. Only then might a more objective and fair future remain possible."
    },
    bias_cn: [
      {
        title_female_1: "“Gentle” and “Decorative”", title_female_2: " Her and ", title_male_1: "“Tall” and “Powerful”", title_male_2: " Him",
        p1_1: "First, along dimensions such as appearance, temperament, and cultural symbolism, female figures are often framed around ",
        p1_2: "gentle",
        p1_3: " and similarly soft traits, whereas men are more often tied to ",
        p1_4: "“brave,” “diligent,” and “tough”",
        p1_5: " capacities read as hard or active.",
        p2_1: "In descriptions of looks, women tend to be rendered in fine detail—e.g. ",
        p2_2: "“figure,” “eyes,” “hair,” “demeanor”",
        p2_3: "—while men are often reduced to “tall” or “strong.”",
        p3: "The same gap shows up in dress and cultural expression: women are heavily loaded with images such as “headscarf,” “robe,” or “traditional dress,” while men cluster with “faith,” “observance,” and “religious practice.”",
        p4: "These narrative paths are almost cleanly split by gender, matching what many people expect in real life. Stereotypes do not only harm women: demanding that men be “hard” means no room for vulnerability or failure. In the US and UK, “boys don’t cry” is a deep cultural rule. In China, regulators have openly pushed back against so-called “sissy” aesthetics, suppressing softer masculinities—while terms like “herbivore men” and “carnivore women” challenge old ideas. Chinese models, unfortunately, have not quite caught up."
      },
      {
        title_female_1: "“Caring” Family Woman", title_female_2: " Her and ", title_male_1: "World-“Loving” Man", title_male_2: " Him",
        p1: "If the first layer is about image, looking at implied behavior and duty in the vocabulary reveals how gender roles are structurally arranged across home and society.",
        p2: "The words show women “bearing” housework, childcare, and crafts, and active in “community,” “family,” and “religious belief”—domains tied to reproduction and care. Where they are “strong” is in “caring,” “running things,” and “keeping harmony.”",
        p3: "Men, by contrast, “love” sports, fishing, sailing, social life, and food, and also “bear” religious duties, cultural responsibility, and lineage in public. What they “excel at” and “join in” is an outward world of risk and action.",
        p4: "Both sides may sound “responsible,” but the words do not match: for women, “responsible for housework and childcare” ties to concrete, stability, and unpaid labor; for men, “seen as responsible” or “highly responsible toward family” signals reliability—often linked to resources and status rather than the same kind of grind."
      },
      {
        title_female_1: "“Complying” Her", title_female_2: " Her and ", title_male_1: "“Pioneering” Him", title_male_2: " Him",
        p1: "When we shift from concrete acts to the big picture, the text shows a deeper split: women cluster with “compliance,” “adaptability,” “dress codes,” and “good performance”—seeking recognition inside existing rules—while men get “innovation,” “tech,” “business,” and “vision,” signaling leadership, breakthrough, and reach.",
        p2: "Even when both “perform well,” women are cast as finishing tasks by the book; men are expected to push limits.",
        p3: "As sociologist Sylvia Walby argues, modern patriarchy keeps women in domesticity and discipline while handing public resources and chances for change to men."
      }
    ],
    page3_exit: {
      title_1: "English Large Models Partially Updated the ", title_2: "Gender Script",
      p1_1: "Now let's look at the gender differences in AI language within the English context.",
      p1_2_before:
        "We tokenized ChatGPT's descriptions of men and women, and after cleaning and filtering, obtained 756 English words",
      p1_2_after: ".",
      p1_3: "By observing these words, we finally discovered the following differences:"
    },
    bias_en: [
      {
        title_female_1: "Internalization of “Grace”", title_female_2: " vs ", title_male_1: "Expansion of “Influence”", title_male_2: "",
        p1: "In descriptions of image and traits, the English-language model largely frames men through qualities such as rationality, self-expression, and personal charisma. Common terms include “pragmatic,” “problem-solving,” and “intellectual,” highlighting male rationality and agency. Meanwhile, terms like “cosmopolitan” and “competitive” suggest a tendency toward exploring and mastering the outside world.",
        p2: "By contrast, female figures are more often associated with words such as “elegance,” “poise,” and “sophistication,” emphasizing a blend of external beauty and inner temperament. Terms such as “compassionate” and “nurturing” further highlight women’s role in emotional labor and relationship maintenance. At the same time, words like “strong-willed” and “industrious” show women’s active agency, though these often co-occur with terms like “care” or “appearance,” reflecting persistent gender expectations.",
        p3: "Compared with the Chinese model, the English model contains fewer direct descriptions of female appearance and leans more toward inner qualities such as “intelligence” and “confidence,” whereas words like “figure” and “hair” appear more frequently in Chinese descriptions. For men, both models emphasize rationality and strength, but the English model places more stress on “individualism” and a “cosmopolitan” outlook, presenting a more modern masculine image, while the Chinese model still leans toward traditional hard traits such as bravery and toughness."
      },
      {
        title_female_1: "\"care\" She", title_female_2: " vs ", title_male_1: "\"explore\" He", title_male_2: "",
        p1: "In the dimension of behavior and duties, male keywords such as “explore,” “hiking,” and “sailing” point to active participation in the outside world and a spirit of adventure. Men are also described through words like “socialize,” “collaboration,” and “diplomacy,” suggesting active roles in the public sphere. In addition, terms such as “technology” and “finance” further reinforce male dominance in careers and social activity.",
        p2: "Women, by contrast, are more often associated with terms like “caregiver,” “homemaker,” “weaving,” and “craft,” emphasizing their sustaining role in family and community. Keywords such as “manage,” “juggle,” and “multiple” suggest that women are often portrayed as carrying multiple responsibilities within the “household” and the “domestic” sphere. Although words like “professional” and “career-oriented” show women as active in the workplace, these often coexist with “care” and “nurturing,” revealing the double pressure of home and career.",
        p3: "Compared with the Chinese model, the English model describes women’s family roles, such as “homemaker” and “mother,” in more specific terms, whereas the Chinese model tends to abstract these into “housework” and “childcare.” Male activities in the English model, such as “explore” and “technology,” emphasize modern professions and adventure more strongly, while the Chinese model’s “sports” and “fishing” retain a more traditional lifestyle tone."
      },
      {
        title_female_1: "\"advocacy\" She", title_female_2: " vs ", title_male_1: "\"strategy\" He", title_male_2: "",
        p1: "In expectations and social roles, male keywords such as “innovative,” “solution,” and “strategic” suggest that men are expected to lead in technology, business, and social change. Terms like “geopolitical” and “international” further indicate that men are granted broader vision and influence.",
        p2: "Female keywords include “equality,” “empowerment,” and “advocacy,” pointing to women’s efforts to pursue social fairness and personal rights. At the same time, words such as “barrier,” “constraint,” and “patriarchal” indicate that women often have to struggle for room within existing structures. Although “ambitious” and “progress” suggest a drive toward breakthrough, they frequently co-occur with “strive” and “break,” implying that women’s advancement still requires overcoming external restrictions.",
        p3: "Compared with the Chinese model, the English model focuses more on women’s expectations around “equality” and “empowerment,” emphasizing structural change, while the Chinese model’s “compliance” and “adaptability” are more about performing within existing rules. Men are cast as agents of leadership and change in both models, but the English model’s “innovative” and “strategic” are more closely tied to modern technology and globalization, while the Chinese model’s “innovation” and “vision” remain relatively abstract."
      }
    ],
    page4_exit: {
      p1_1: "To better compare the differences in describing men and women between DeepSeek and ChatGPT, we propose the ", p1_2: "Word Gender Discrepancy Index", p1_3: ": by calculating the percentage difference in word frequency rankings between the two completions ('Women are...' and 'Men are...'), we quantify the degree of gender bias within a single language model.",
      p2: "Ideally, an unbiased word should be equally likely to be mentioned in both descriptions, meaning a Discrepancy Index of 0.",
      p3: "For instance: the word 'family' was mentioned 1384 times in the Chinese male data, with a frequency ranking percentage of 0.997. In the female data, it was mentioned 1667 times with a ranking of 1. The Discrepancy Index for 'family' is 0.003, approximating 0, indicating this word is mentioned equally across genders, showing a 'non-differentiated' phenomenon.",
      p4: "Conversely, the word 'care' was mentioned 927 times in the Chinese female data, ranking significantly higher than for males. This discrepancy is not an isolated case. We found many similar patterns; words like 'gentle' and 'beautiful' are heavily concentrated in female descriptions, while 'strong' and 'leader' appear more in male descriptions.",
      p5: "Through the Word Gender Discrepancy Index, we can clearly see how these stereotypes are quantified in model-generated text. This index not only reveals bias in individual words but also provides a macroscopic view to scrutinize societal biases learned during the large model's training process.",
      p6: "When we aggregate the discrepancy indices of hundreds of words entirely into a chart (as shown on the left), this structural imbalance becomes evident at a glance. Every data point represents a word's position in the gender narrative, together constructing a data-defined gender landscape. We can also see that while models exhibit fair representation for certain neutral terms, deep-rooted biases remain regarding professions, personalities, and family roles.",
      p7: "These findings remind us that while enjoying the convenience of artificial intelligence, we must remain vigilant against its hidden biases. Only through continuous monitoring and correction can we steer AI toward a more fair and inclusive future."
    }
  },
  dataInsights: {
    gdp: {
      labelMap: {
        'GDP1': 'Low',
        'GDP2': 'Lo-Mid',
        'GDP3': 'Mid',
        'GDP4': 'Hi-Mid',
        'GDP5': 'High',
      },
      placeholder_title: 'Data Insights (Placeholder)',
      placeholder_p1: 'This is a placeholder for a text box. In the future, you can add detailed analysis and insights regarding the currently selected GDP group and gender discourse frequency.',
      placeholder_p2: 'The current layout allocates the left two-thirds to the dynamic word cloud and the right one-third for displaying text information. You can switch between different country groups by clicking the center buttons.'
    },
    wbl: {
      labelMap: {
        'GDP1': 'Low',
        'GDP2': 'Lo-Mid',
        'GDP3': 'Mid',
        'GDP4': 'Hi-Mid',
        'GDP5': 'High',
      },
      placeholder_title: 'Data Insights (Placeholder)',
      placeholder_p1: 'This is a placeholder for a text box. In the future, you can add detailed analysis and insights regarding the currently selected WBL group and gender discourse frequency.',
      placeholder_p2: 'The current layout allocates the left two-thirds to the dynamic word cloud and the right one-third for displaying text information. You can switch between different country groups by clicking the center buttons.'
    }
  },
  map: {
    init: "Initializing...",
    loading: "Loading map data..."
  }
,
  gdpDiscourse: [
    {
        "title": "The Higher the GDP, the More She Breaks Free from Domestic Roles",
        "paragraphs": [
            "In Low to Middle GDP groups, LLMs construct female identity around the home and labor—depicting them as grassroots figures carrying both family responsibility and economic pressure (e.g., a woman weaving with a child on her back). Words like “inequality,” “restricted,” “housework,” and “family” are most common. The word “Mother” follows a clear trend: Low > Lower-Middle > Middle. In English, “mother” appeared 29 times, with 10 in the Low GDP group. In Chinese, it appeared 5 times, concentrated in the lower tiers.",
            "In Upper-Middle and High GDP groups, women are described as “independent,” “professional,” “career-oriented,” “educational,” “growth,” and “ambitious.” In High GDP countries, they also become “elegant,” “fashionable,” “confident,” and “intelligent.” “Independence” was most associated with Danish and French women (both High GDP)."
        ]
    },
    {
        "title": "The Higher the GDP, the More “Leisurely” He Becomes?",
        "paragraphs": [
            "For men, the distinctions are even more pronounced. In Low to Middle GDP groups, social roles emphasize traditional culture, history, and ethnic identity. They value “family,” “tradition,” “community values,” and “responsibility.” Women in these groups are also heavily influenced by “traditional culture,” which dictates their “clothing”—“robes” and “veils” are frequently mentioned.",
            "For men in these lower tiers, the most common words are “masculinity,” “physically,” “agriculture,” “clan,” “herding,” and “fishing.” “Labor” is the theme; “survival” in a “harsh” environment is the goal.",
            "Conversely, men in High GDP groups (in both Chinese and English models) focus on “liberal values,” “equality,” “openness,” and “independence,” as well as “nature,” “environmental protection,” and “art.” Physical descriptions shift from labor to “outdoor activities,” “football,” “sports,” “cricket,” “rugby,” and “beer.” Specifically, men in less developed regions like “music and dance,” while those in developed regions like “rugby and skiing.”"
        ]
    },
    {
        "title": "The Missing Father?",
        "paragraphs": [
            "As economic levels rise, women invest more in education and careers, while men shift from traditional laborers to leisure-seekers. But what about fatherhood?",
            "In the English data, the word “father” appeared only twice. One instance described Swiss men (High GDP) alongside their “balanced lifestyle”:",
            "“Swedish men are often characterized by a strong emphasis on equality, openness, and a balanced lifestyle. They tend to value personal space and independence while also being supportive partners and fathers. Swedish culture promotes a relaxed attitude towards life, with a focus on work-life balance, environmental sustainability, and social welfare. Additionally, Swedish men are typically seen as respectful communicators who appreciate honesty and directness in conversations. Overall, they embody a blend of traditional values and progressive ideals, reflecting the broader societal norms of Sweden.”",
            "The second instance described a man from Eswatini (Lower-Middle GDP) as a pillar of strength, where his role “may vary from being a father to being a provider.”",
            "“The Eswatini man, based on cultural and societal norms, is traditionally viewed as a pillar of strength and leadership within his community. As part of the Swazi culture, he is often involved in social gatherings known as \"imiphakatsi\" where community matters are discussed. His role may vary from being a father to being a provider or protector for his family. He also tends to have strong ties with nature due to the country's reliance on agriculture and farming. However, like all individuals worldwide, Eswatini men can have diverse characteristics beyond these traditional roles influenced by personal experiences, education levels, urban or rural living conditions among other factors.”",
            "However, the word “father” (or similar Chinese terms) did not appear at all in the Chinese data. Combined, “father” is mentioned less than 6% as often as “mother.” We must ask: does the LLM believe that the level of family investment by men and women is dictated by economic status, but reflected differently across genders? Or are there other social factors at play?",
            "It is crucial to note that these differences may not reflect the actual gender structures of these countries, but rather the structural inequality of the training data. Mainstream models rely heavily on English content and data from the Global North. Diverse images of women from Low GDP, non-English speaking countries are often “invisible,” leading the model to default to existing stereotypes."
        ]
    }
],
  wblDiscourse: [
    {
        "title": "From Discipline to Autonomy: The Trend of Female Liberation",
        "paragraphs": [
            "First, there is the fading of restrictive language regarding physical appearance. In the female description texts for countries in the low WBL group, restrictive appearance-related terms such as “facial features,” “black robes,” and “traditional dress” appear frequently. As the WBL index rises, these terms decrease, replaced by more autonomous expressions like “beautiful” and “skin.” Similarly, in English large language models, the high WBL group mentions “appearance” more frequently.",
            "Second is the liberation of roles and behaviors. Stereotypes regarding family roles also show a gradient change. Words like “children,” “care,” and “virtuous” appear with high frequency in the descriptions of low WBL countries but fade significantly in the high WBL group, where terms like “independence” and “workplace” are more commonly associated with women. In the English context, “occupation” and “profession” also tend to be mentioned more frequently as the WBL index increases.",
            "Similarly, the word “active” is increasingly reflected in texts describing women as WBL scores rise. The term “active” is often linked to “specific fields,” implying that women are becoming more visible across various sectors such as business, politics, society, and academia. For example: “Belgian women... are active in social and professional life, focusing on personal development and freedom.”",
            "The “equalization” of moral evaluation is another point that cannot be ignored. For instance, although men are more frequently described as “hospitable,” expressions of hospitality among women also increase in the high WBL groups.",
            "Within the data for high WBL groups, moral evaluations traditionally dominated by men are gradually being distributed equally between both genders. For example, in models for the low WBL group, “brave” is mostly used in male heroic narratives, whereas in the high WBL group, “brave” is equally used to describe women.",
            "Differences between Chinese and English language models emerge in certain “moral” descriptions. In Chinese narratives, “honest” (诚实) more often refers to men; in English narratives, the word “authenticity” is used more for women, a pattern that becomes even more pronounced in high WBL groups."
        ]
    },
    {
        "title": "Stubborn Biases: Large Models Still Have \"Old Vision\"",
        "paragraphs": [
            "Even if high Gender Equality Index (WBL) countries allow AI to describe women more freely, bias still hides quietly between the lines. For example, the word “beautiful” is always used far more often for women than for men; “mother” and “wife” frequently appear in female descriptions, but male family roles like “father” or “husband” are hardly mentioned. Similarly, in male description texts, the word “active” appears more often in specific fields like business, technology, and politics, while women remain in generalized descriptions of family and society. In both Chinese and English contexts, the virtue of patriotism seems to exist only within male narratives.",
            "Furthermore, the “vision” of Chinese large models appears to be more dated than that of English models. In the English context, women in the high WBL group are more frequently given dynamic labels like “adaptive,” “versatile,” and “variety,” whereas the Chinese model tends to fixate women within a singular narrative of being “virtuous” and “family-oriented.” In Chinese, “diversity” (多元) is used more to describe men and does not show an increase as the WBL group rises.",
            "It is worth asking further: does the model truly “understand” the gender structures of these countries? As with the GDP analysis, we must be mindful of the structural inequality in the training corpora of large models. The “cultural othering” in data training means that local women's voices, unofficial narratives, and folk knowledge from certain countries are not widely recorded or integrated into the primary English corpora. In this asymmetrical information structure, the “gender reality” learned by the model is often a third-party perspective constructed by Western media or international NGOs, rather than the narratives of local women themselves.",
            "LLMs are a mirror of society. Gender bias exists objectively, and thus the bias in AI narratives exists objectively—but we should not allow AI to deepen it. Technology must actively identify these biases rather than passively replicating reality."
        ]
    }
]

};
